#!/bin/bash

# git stuff
alias gs="git status"
alias gc="git commit"
alias ga="git add"
alias gl="git log"
alias glo="gl --oneline --graph --decorate --color"
alias gd="git diff"
alias gst="git stash"
alias gstp="git stash pop"
alias gstd="git stash drop"
#alias gcd="cd '$(git rev-parse --show-toplevel)'"

# pacman stuff
alias pacupg='sudo pacman -Syu'
alias pacin='sudo pacman -S'
alias pacrm='sudo pacman -Rns'
alias paclean='sudo pacman -Sc'
alias pacsearch='pacman -Ss'
alias pacsize='expac -H M "%011m\t%-20n\t%10d" $(comm -23 <(pacman -Qqen | sort) <(pacman -Qqg base base-devel | sort)) | sort -n'

# colors for programs
alias ls='ls --color=auto --group-directories-first'
alias grep='grep --color=auto'

# other stuff
alias vim="nvim"
alias irkk="mosh joelto@hubben.chalmers.it"
alias reload=". ~/.bashrc"
alias svim="sudo -E nvim "
alias reloadxres="xrdb ~/.config/xresources"
alias re="urxvt&"
alias blank="feh -F ~/.config/bash/black.png"
alias matlab="matlab -nodesktop -nosplash"
alias open="xdg-open"
alias android-mount="simple-mtpfs /media/phone/"
alias android-umount="fusermount -u /media/phone"
alias safari-debug="ios_webkit_debug_proxy -f chrome-devtools://devtools/bundled/inspector.html"

