#!/bin/bash

source /usr/share/git/git-prompt.sh

status="$"
git_branch=""
columns=$(tput cols)

PS1='\n\e[1;90m $status \e[0;94m${newPWD} \e[0;35m$git_branch\e[0;90m\e[0m \n'

function prompt_command {
    es=$?
    status='$'
    if [ $es -ne 0 ]
    then
        status=$'\e[1;31m!'
    fi

    git_branch=$(__git_ps1 "(%s)")

    let fillsize=$COLUMNS-${#git_branch}-5

    if [ $HOME == $PWD ]
	then
	  newPWD="~"
	elif [ $HOME ==  ${PWD:0:${#HOME}} ]
	then
	  newPWD="~${PWD:${#HOME}}"
	else
	  newPWD=$PWD
	fi

	 local pwdmaxlen=$((fillsize-2))
	 if [ ${#newPWD} -gt $pwdmaxlen ]
	 then
	    local pwdoffset=$(( ${#newPWD} - $pwdmaxlen  ))
		newPWD="..${newPWD:$pwdoffset:$pwdmaxlen}"
	fi
} 2> /dev/null
export PROMPT_COMMAND=prompt_command
